apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: debug-app
  name: debug-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: debug-app
  template:
    metadata:
      annotations:
      labels:
        name: debug-app
    spec:
      containers:
      - image: quay.io/wcaban/net-toolbox:latest
        name: debug-app
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
