apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "resource-limits-pod"
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "600"
        memory: "2Gi"
      min:
        cpu: "10m"
        memory: "4Mi"
      maxLimitRequestRatio:
        cpu: "100"
---
apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "resource-limits-container"
spec:
  limits:
    - type: "Container"
      max:
        cpu: "300"
        memory: "1Gi"
      min:
        cpu: "5m"
        memory: "4Mi"
      default:
        cpu: "100m"
        memory: "100Mi"
      defaultRequest:
        cpu: "100m"
        memory: "100Mi"
      maxLimitRequestRatio:
        cpu: "300"
