apiVersion: v1
kind: Service
metadata:
  name: open5gs-udm
  labels:
    epc-mode: udm
spec:
  selector:
    epc-mode: udm
  ports:
    - protocol: TCP
      port: 80   
      targetPort: 80
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-udm-d
  labels:
    epc-mode: udm
spec:
  #replicas: 1
  selector:
    matchLabels:
      epc-mode: udm
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        epc-mode: udm
    spec:   
      containers:
        - name: udm
          image: "{{ .Values.open5gcore.image.repository }}:{{ .Values.open5gcore.image.oldtag }}"
          imagePullPolicy: {{ .Values.open5gcore.image.pullPolicy }}
          command: ["open5gs-udmd", "-c", "/open5gs/config-map/udm.yaml"]
          volumeMounts:
          - name: open5gs-udm-config
            mountPath: /open5gs/config-map/udm.yaml
            subPath: "udm.yaml"
      volumes:
        - name: open5gs-udm-config
          configMap:
            name: open5gs-udm-config
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: open5gs-udm-d
spec:
  maxReplicas: 7
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: open5gs-udm-d
  targetCPUUtilizationPercentage: 60
