apiVersion: v1
kind: Service
metadata:
  name: open5gs-udr
  labels:
    epc-mode: udr
spec:
  selector:
    epc-mode: udr
  ports:
    - protocol: TCP
      port: 80   
      targetPort: 80
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-udr-d
  labels:
    epc-mode: udr
spec:
  #replicas: 1
  selector:
    matchLabels:
      epc-mode: udr
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        epc-mode: udr
    spec:   
      containers:
        - name: udr
          image: "{{ .Values.open5gcore.image.repository }}:{{ .Values.open5gcore.image.oldtag }}"
          imagePullPolicy: {{ .Values.open5gcore.image.pullPolicy }}
          command: ["open5gs-udrd", "-d", "-c", "/open5gs/config-map/udr.yaml"]
          volumeMounts:
          - name: open5gs-udr-config
            mountPath: /open5gs/config-map/udr.yaml
            subPath: "udr.yaml"          
      volumes:
        - name: open5gs-udr-config
          configMap:
            name: open5gs-udr-config
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: open5gs-udr-d
spec:
  maxReplicas: 7
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: open5gs-udr-d
  targetCPUUtilizationPercentage: 60
