apiVersion: v1
kind: Service
metadata:
  name: amf-open5gs-sctp
  labels:
    epc-mode: amf
    version: v2
spec:
  type: NodePort
  selector:
    epc-mode: amf
  ports:
    - protocol: SCTP
      port: 38412
      targetPort: 38412
      nodePort: 30412
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-amf
  labels:
    epc-mode: amf
    version: v2
spec:
  type: NodePort
  selector:
    epc-mode: amf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080    
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-sctp-on-http
spec:
  podSelector:
    matchLabels:
      epc-mode: amf
      version: v2
  ingress:
  - ports:
    - protocol: SCTP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-amf-d
  labels:
    epc-mode: amf
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: amf
      version: v2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        epc-mode: amf
        version: v2
    spec:    
      containers:
        - name: amf
          image: "docker.io/efatnar/open5gcore:v1.1"
          imagePullPolicy: IfNotPresent
          command: ["open5gs-amfd", "-d", "-c", "/open5gs/config-map/amf.yaml"]
          volumeMounts:
          - name: open5gs-amf-config
            mountPath: /open5gs/config-map/amf.yaml
            subPath: "amf.yaml"
      volumes:
        - name: open5gs-amf-config
          configMap:
            name: open5gs-amf-config
