kind: ExportedServiceSet
apiVersion: federation.maistra.io/v1
metadata:
  name: prod1-mesh
  namespace: prod2-mesh
spec:
  exportRules:
  - type: LabelSelector
    labelSelector:
      namespace: prod2-5gcore
      selector:
        matchLabels:
          app: details
      alias:
        namespace: 5gcore
