kind: ServiceMeshPeer
apiVersion: federation.maistra.io/v1
metadata:
  name: prod1-mesh
  namespace: prod2-mesh
spec:
  remote:
    addresses:
    - prod2-mesh-ingress.prod2-mesh.svc.cluster.local
    discoveryPort: 8188
    servicePort: 15443
  gateways:
    ingress:
      name: prod1-mesh-ingress
    egress:
      name: prod1-mesh-egress
  security:
    trustDomain: prod1-mesh.local
    clientID: prod1-mesh.local/ns/prod1-mesh/sa/prod2-mesh-egress-service-account
    certificateChain:
      kind: ConfigMap
      name: prod1-mesh-ca-root-cert
